FROM python:3.10-slim

# Telechargement automatique des poids des modeles depuis le drive
WORKDIR /app

RUN pip install --no-cache-dir gdown

RUN mkdir -p weights && \
    gdown --id 13cufbIVuBbY3s5Q97gULYCCcpx3U1KLr -O weights/poster_classifier_resnet.pth && \
    gdown --id 1gNdApWLh_83YNnyUcDmio2PwWAPijvxB -O weights/text_classifier.pth && \
    gdown --id 1pDzDyHeH-nRU2a9bI6KlFs7PLxaLzCoF -O weights/dknn.pkl

RUN mkdir -p embeddings && \
    gdown --id 16OEnpILRMhIysFlwDNAUMA5-SQ1GpVbp -O embeddings/movie_plots.ann && \
    gdown --id 1xSPjkratx8XX8NlRiP30waXrZHlYQBf_ -O embeddings/movie_plots_index.csv

RUN mkdir -p assets && \
    gdown --id 1PeKtyaYANp-D2-i8DX8AZ2h65qIEhIqU -O assets/metadata.json && \
    gdown --id 18qk0Fx4cgWYdVz2o1qXyKja6JUhcJByc -O assets/movies.ann

# (optionnel mais souvent utile)
RUN python -m pip install --no-cache-dir --upgrade pip setuptools wheel

# 1) copier d'abord les requirements pour profiter du cache
COPY requirements-api.txt /app/requirements-api.txt

# ajout pour pouvoir utiliser annoy
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements-api.txt

#ajout pour pouvoir utiliser clip
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir \
    "setuptools<70" \
    wheel

# Install CLIP without pip build isolation
RUN git clone https://github.com/openai/CLIP.git /tmp/CLIP && \
    cd /tmp/CLIP && \
    python setup.py install && \
    rm -rf /tmp/CLIP


# 2) copier le reste
COPY . /app

EXPOSE 5075

CMD ["python", "genre_pred_api.py", "--poster_classifier_path", "weights/poster_classifier_resnet.pth", "--text_classifier_path", "weights/text_classifier.pth", "--dknn_path", "weights/dknn.pkl", "--annoy_path", "embeddings/movie_plots.ann", "--annoy_meta_path", "embeddings/movie_plots_index.csv", "--labels_path", "labels.json", "--mm_annoy_path", "assets/movies.ann", "--mm_metadata_path", "assets/metadata.json"]